version: "3"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: advertising
    healthcheck:
      test: pg_isready -U user -d advertising
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build:
      dockerfile: build/Dockerfile
    environment:
      HOST: 0.0.0.0:8080
      DATABASE_URL: postgres://user:pass@postgres/advertising
      RUST_LOG: debug
    depends_on:
      - postgres
    ports:
      - 8080:8080
    links:
      - postgres
